### ISSUE TITLE
Display of created apartment page

### ISSUE THREAD

**Issue by priyadharshiniraju** [vasanthakumar-a/Apartment_Rental_Rails#11]
In the display of created apartment page it shows water supply is zero and we can't update it

**Comment by mithun30052001** [comment]
The bug is fixed and i have attached the screenshots below
![Screenshot from 2022-10-28 10-10-12](https://user-images.githubusercontent.com/81811776/198505036-709e28af-73d1-46b2-baa3-c5e91915771c.png)
![Screenshot from 2022-10-28 10-10-19](https://user-images.githubusercontent.com/81811776/198505057-08e62180-ebdc-48f9-b487-36ebd7db2ff0.png)
